parameters: ~
services:
  jigoshop.admin.page_resolver:
    class: Jigoshop\Admin\PageResolver
    arguments:
      - '@wpal'
  jigoshop.admin.page.orders:
    class: Jigoshop\Admin\Page\Orders
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.order'
      - '@jigoshop.helper.styles'
      - '@jigoshop.helper.scripts'
  jigoshop.admin.page.order:
    class: Jigoshop\Admin\Page\Order
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.order'
      - '@jigoshop.service.tax'
      - '@jigoshop.service.customer'
      - '@jigoshop.service.shipping'
      - '@jigoshop.helper.styles'
      - '@jigoshop.helper.scripts'
  jigoshop.admin.page.products:
    class: Jigoshop\Admin\Page\Products
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.product'
