parameters: ~
services:
  jigoshop.admin.settings.general:
    class: Jigoshop\Admin\Settings\GeneralTab
    arguments:
      - '@jigoshop.options'
    tags:
      - { name: jigoshop.admin.settings.tab }
  jigoshop.admin.settings.shopping:
    class: Jigoshop\Admin\Settings\ShoppingTab
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.helper.scripts'
    tags:
      - { name: jigoshop.admin.settings.tab }
  jigoshop.admin.settings.taxes:
    class: Jigoshop\Admin\Settings\TaxesTab
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.tax'
      - '@jigoshop.helper.scripts'
    tags:
      - { name: jigoshop.admin.settings.tab }
  jigoshop.admin.settings.shipping:
    class: Jigoshop\Admin\Settings\ShippingTab
    arguments:
      - '@jigoshop.options'
      - '@jigoshop.service.shipping'
      - '@jigoshop.helper.scripts'
    tags:
      - { name: jigoshop.admin.settings.tab }
  jigoshop.admin.settings.payment:
    class: Jigoshop\Admin\Settings\PaymentTab
    arguments:
      - '@jigoshop.options'
      - '@jigoshop.service.payment'
    tags:
      - { name: jigoshop.admin.settings.tab }
