parameters: ~
services:
  jigoshop.admin.settings.general:
    class: Jigoshop\Admin\Settings\GeneralTab
    arguments:
      - '@wpal'
      - '@jigoshop.options'
    tags:
      - { name: jigoshop.admin.settings.tab }
  jigoshop.admin.settings.shopping:
    class: Jigoshop\Admin\Settings\ShoppingTab
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.messages'
    tags:
      - { name: jigoshop.admin.settings.tab }
  jigoshop.admin.settings.products:
    class: Jigoshop\Admin\Settings\ProductsTab
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.messages'
    tags:
      - { name: jigoshop.admin.settings.tab }
  jigoshop.admin.settings.taxes:
    class: Jigoshop\Admin\Settings\TaxesTab
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.tax'
    tags:
      - { name: jigoshop.admin.settings.tab }
  jigoshop.admin.settings.shipping:
    class: Jigoshop\Admin\Settings\ShippingTab
    arguments:
      - '@jigoshop.options'
      - '@jigoshop.service.shipping'
    tags:
      - { name: jigoshop.admin.settings.tab }
  jigoshop.admin.settings.payment:
    class: Jigoshop\Admin\Settings\PaymentTab
    arguments:
      - '@jigoshop.options'
      - '@jigoshop.service.payment'
    tags:
      - { name: jigoshop.admin.settings.tab }
  jigoshop.admin.settings.advanced:
    class: Jigoshop\Admin\Settings\AdvancedTab
    arguments:
      - '@wpal'
      - '@service_container'
      - '@jigoshop.options'
      - '@jigoshop.messages'
    tags:
      - { name: jigoshop.admin.settings.tab }
