parameters: ~
services:
  jigoshop.admin:
    class: Jigoshop\Admin
    arguments:
      - '@wpal'
      - '@jigoshop.admin.dashboard'
      - '@jigoshop.admin.permalinks'
  jigoshop.admin.pages:
    class: Jigoshop\Admin\Pages
    arguments:
      - '@wpal'
      - '@jigoshop.options'
  jigoshop.admin.permalinks:
    class: Jigoshop\Admin\Permalinks
    arguments:
      - '@wpal'
      - '@jigoshop.options'
  jigoshop.admin.dashboard:
    class: Jigoshop\Admin\Dashboard
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.order'
      - '@jigoshop.service.product'
    tags:
      - { name: jigoshop.admin.page }
  jigoshop.admin.reports:
    class: Jigoshop\Admin\Reports
    tags:
      - { name: jigoshop.admin.page }
    arguments:
      - '@wpal'
      - '@jigoshop.messages'
      - '@jigoshop.service.order'
  jigoshop.admin.settings:
    class: Jigoshop\Admin\Settings
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.messages'
    tags:
      - { name: jigoshop.admin.page }
  jigoshop.admin.system_info:
    class: Jigoshop\Admin\SystemInfo
    arguments:
      - '@wpal'
    tags:
      - { name: jigoshop.admin.page }
  jigoshop.admin.licences:
    class: Jigoshop\Admin\Licences
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.messages'
    tags:
      - { name: jigoshop.admin.page }
  jigoshop.admin.migration:
    class: Jigoshop\Admin\Migration
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.messages'
    tags:
      - { name: jigoshop.admin.page }
  jigoshop.admin.product.attributes:
    class: Jigoshop\Admin\Product\Attributes
    arguments:
      - '@wpal'
      - '@jigoshop.messages'
      - '@jigoshop.service.product'
    tags:
      - { name: jigoshop.admin.page }
