parameters: ~
services:
  jigoshop.factory.order_service:
    class: Jigoshop\Factory\OrderService
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.factory.order'
  jigoshop.factory.product_service:
    class: Jigoshop\Factory\ProductService
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.factory.product'
  jigoshop.factory.variable_product_service:
    class: Jigoshop\Factory\Product\VariableService
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.product'
  jigoshop.factory.tax_service:
    class: Jigoshop\Factory\TaxService
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.customer'
  jigoshop.factory.customer_service:
    class: Jigoshop\Factory\CustomerService
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.factory.customer'
  jigoshop.factory.product:
    class: Jigoshop\Factory\Product
    arguments:
      - '@wpal'
      - '@jigoshop.options'
  jigoshop.factory.product.variable:
    class: Jigoshop\Factory\Product\Variable
    arguments:
      - '@wpal'
      - '@jigoshop.service.product'
  jigoshop.factory.order:
    class: Jigoshop\Factory\Order
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.customer'
      - '@jigoshop.service.product'
      - '@jigoshop.service.shipping'
      - '@jigoshop.service.payment'
      - '@jigoshop.service.tax'
  jigoshop.factory.customer:
    class: Jigoshop\Factory\Customer
    arguments:
      - '@wpal'
  jigoshop.factory.shipping_service:
    class: Jigoshop\Factory\ShippingService
    arguments:
      - '@wpal'
      - '@jigoshop.options'
  jigoshop.factory.payment_service:
    class: Jigoshop\Factory\PaymentService
    arguments:
      - '@wpal'
      - '@jigoshop.options'
