parameters: ~
services:
  jigoshop.helper.styles:
    class: Jigoshop\Helper\Styles
    arguments:
      - '@wpal'
  jigoshop.helper.scripts:
    class: Jigoshop\Helper\Scripts
    arguments:
      - '@wpal'
