parameters: ~
services:
  wpal:
    class: WPAL\Wordpress
  jigoshop:
    class: Jigoshop\Core
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.messages'
      - '@jigoshop.pages'
      - '@jigoshop.template'
  jigoshop.installer:
    class: Jigoshop\Core\Installer
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.cron'
      - '@jigoshop.emails'
  jigoshop.options:
    class: Jigoshop\Core\Options
    arguments:
      - '@wpal'
  jigoshop.cron:
    class: Jigoshop\Core\Cron
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.order'
      - '@jigoshop.service.email'
  jigoshop.emails:
    class: Jigoshop\Core\Emails
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.email'
  jigoshop.api:
    class: Jigoshop\Api
    arguments:
      - '@wpal'
    tags:
      - { name: jigoshop.container_aware }
  jigoshop.pages:
    class: Jigoshop\Core\Pages
    arguments:
      - '@wpal'
      - '@jigoshop.options'
  jigoshop.messages:
    class: Jigoshop\Core\Messages
    arguments:
      - '@wpal'
  jigoshop.types:
    class: Jigoshop\Core\Types
    arguments:
      - '@wpal'
  jigoshop.roles:
    class: Jigoshop\Core\Roles
    arguments:
      - '@wpal'
  jigoshop.assets:
    class: Jigoshop\Core\Assets
    arguments:
      - '@wpal'
      - '@jigoshop.pages'
      - '@jigoshop.options'
      - '@jigoshop.helper.styles'
      - '@jigoshop.helper.scripts'
  jigoshop.template:
    class: Jigoshop\Core\Template
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.pages'
  jigoshop.cart:
    class: Jigoshop\Frontend\Cart
    scope: prototype
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.product'
      - '@jigoshop.service.tax'
      - '@jigoshop.service.shipping'
  jigoshop.permalinks:
    class: Jigoshop\Core\Permalinks
    arguments:
      - '@wpal'
      - '@jigoshop.options'
  jigoshop.post_type.product:
    class: Jigoshop\Core\Types\Product
    arguments:
      - '@di'
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.product'
    tags:
      - { name: jigoshop.type.post }
  jigoshop.post_type.email:
    class: Jigoshop\Core\Types\Email
    arguments:
      - '@wpal'
    tags:
      - { name: jigoshop.type.post }
  jigoshop.post_type.coupon:
    class: Jigoshop\Core\Types\Coupon
    arguments:
      - '@wpal'
    tags:
      - { name: jigoshop.type.post }
  jigoshop.taxonomy.product_category:
    class: Jigoshop\Core\Types\ProductCategory
    arguments:
      - '@jigoshop.options'
    tags:
      - { name: jigoshop.type.taxonomy }
  jigoshop.taxonomy.product_tag:
    class: Jigoshop\Core\Types\ProductTag
    arguments:
      - '@jigoshop.options'
    tags:
      - { name: jigoshop.type.taxonomy }
  jigoshop.post_type.order:
    class: Jigoshop\Core\Types\Order
    arguments:
      - '@wpal'
    tags:
      - { name: jigoshop.type.post }
  jigoshop.product_type.simple:
    class: Jigoshop\Core\Types\Product\Simple
    arguments:
      - '@wpal'
  jigoshop.product_type.variable:
    class: Jigoshop\Core\Types\Product\Variable
    arguments:
      - '@wpal'
      - '@jigoshop.service.product'
      - '@jigoshop.service.product.variable'
      - '@jigoshop.factory.product.variable'
