parameters: ~
services:
  jigoshop.query.interceptor:
    class: Jigoshop\Query\Interceptor
    arguments:
      - '@wpal'
      - '@jigoshop.options'
  jigoshop.page_resolver:
    class: Jigoshop\Core\PageResolver
    arguments:
      - '@wpal'
      - '@jigoshop.pages'
  jigoshop.page.product_list:
    class: Jigoshop\Frontend\Page\ProductList
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.product'
      - '@jigoshop.service.cart'
      - '@jigoshop.messages'
      - '@jigoshop.helper.styles'
      - '@jigoshop.helper.scripts'
  jigoshop.page.product_category_list:
    class: Jigoshop\Frontend\Page\ProductCategoryList
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.product'
      - '@jigoshop.service.cart'
      - '@jigoshop.messages'
      - '@jigoshop.helper.styles'
      - '@jigoshop.helper.scripts'
  jigoshop.page.product_tag_list:
    class: Jigoshop\Frontend\Page\ProductTagList
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.product'
      - '@jigoshop.service.cart'
      - '@jigoshop.messages'
      - '@jigoshop.helper.styles'
      - '@jigoshop.helper.scripts'
  jigoshop.page.product:
    class: Jigoshop\Frontend\Page\Product
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.product'
      - '@jigoshop.service.cart'
      - '@jigoshop.messages'
      - '@jigoshop.helper.styles'
      - '@jigoshop.helper.scripts'
  jigoshop.page.cart:
    class: Jigoshop\Frontend\Page\Cart
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.messages'
      - '@jigoshop.service.cart'
      - '@jigoshop.service.product'
      - '@jigoshop.helper.styles'
      - '@jigoshop.helper.scripts'
