parameters: ~
services:
  jigoshop.payment.cheque:
    class: Jigoshop\Payment\Cheque
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.customer'
    tags:
      - { name: jigoshop.payment.method }

  jigoshop.payment.on_delivery:
    class: Jigoshop\Payment\OnDelivery
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.customer'
    tags:
      - { name: jigoshop.payment.method }
