parameters: ~
services:
  jigoshop.service.order:
    class: Jigoshop\Service\Order
    factory_service: jigoshop.factory.order_service
    factory_method: getService
  jigoshop.service.product:
    class: Jigoshop\Service\Product
    factory_service: jigoshop.factory.product_service
    factory_method: getService
  jigoshop.service.tax:
    class: Jigoshop\Service\Tax
    factory_service: jigoshop.factory.tax_service
    factory_method: getService
  jigoshop.service.customer:
    class: Jigoshop\Service\Customer
    factory_service: jigoshop.factory.customer_service
    factory_method: getService
  jigoshop.service.cart:
    class: Jigoshop\Service\CartService
    arguments:
      - '@wpal'
