parameters: ~
services:
  wpal:
    class: WPAL\Wordpress
  jigoshop:
    class: Jigoshop\Core
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.messages'
      - '@jigoshop.pages'
      - '@jigoshop.template'
      - '@jigoshop.admin'
  jigoshop.installer:
    class: Jigoshop\Core\Installer
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.cron'
  jigoshop.options:
    class: Jigoshop\Core\Options
    arguments:
      - '@wpal'
  jigoshop.cron:
    class: Jigoshop\Core\Cron
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.order'
  jigoshop.pages:
    class: Jigoshop\Core\Pages
    arguments:
      - '@wpal'
      - '@jigoshop.options'
  jigoshop.messages:
    class: Jigoshop\Core\Messages
    arguments:
      - '@wpal'
  jigoshop.types:
    class: Jigoshop\Core\Types
    arguments:
      - '@wpal'
  jigoshop.roles:
    class: Jigoshop\Core\Roles
    arguments:
      - '@wpal'
  jigoshop.assets:
    class: Jigoshop\Core\Assets
    arguments:
      - '@wpal'
      - '@jigoshop.pages'
      - '@jigoshop.options'
      - '@jigoshop.helper.styles'
      - '@jigoshop.helper.scripts'
  jigoshop.page_resolver:
    class: Jigoshop\Core\PageResolver
    arguments:
      - '@wpal'
      - '@jigoshop.pages'
  jigoshop.template:
    class: Jigoshop\Core\Template
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.pages'
  jigoshop.query.interceptor:
    class: Jigoshop\Query\Interceptor
    arguments:
      - '@wpal'
      - '@jigoshop.options'
  jigoshop.page.product_list:
    class: Jigoshop\Frontend\Page\ProductList
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.product'
      - '@jigoshop.helper.styles'
  jigoshop.post_type.product:
    class: Jigoshop\Core\Types\Product
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.product'
    tags:
      - { name: jigoshop.type.post }
  jigoshop.taxonomy.product_category:
    class: Jigoshop\Core\Types\ProductCategory
    tags:
      - { name: jigoshop.type.taxonomy }
  jigoshop.taxonomy.product_tag:
    class: Jigoshop\Core\Types\ProductTag
    tags:
      - { name: jigoshop.type.taxonomy }
  jigoshop.helper.styles:
    class: Jigoshop\Helper\Styles
    arguments:
      - '@wpal'
      - '@jigoshop.pages'
  jigoshop.helper.scripts:
    class: Jigoshop\Helper\Scripts
    arguments:
      - '@wpal'
      - '@jigoshop.pages'
  jigoshop.factory.order_service:
    class: Jigoshop\Factory\OrderService
    arguments:
      - '@wpal'
      - '@jigoshop.options'
  jigoshop.factory.product_service:
    class: Jigoshop\Factory\ProductService
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.factory.product'
  jigoshop.factory.tax_service:
    class: Jigoshop\Factory\TaxService
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.customer'
  jigoshop.factory.customer_service:
    class: Jigoshop\Factory\CustomerService
    arguments:
      - '@wpal'
      - '@jigoshop.options'
  jigoshop.factory.product:
    class: Jigoshop\Factory\Product
    arguments:
      - '@wpal'
  jigoshop.service.order:
    class: Jigoshop\Service\Order
    factory_service: jigoshop.factory.order_service
    factory_method: getService
  jigoshop.service.product:
    class: Jigoshop\Service\Product
    factory_service: jigoshop.factory.product_service
    factory_method: getService
  jigoshop.service.tax:
    class: Jigoshop\Service\Tax
    factory_service: jigoshop.factory.tax_service
    factory_method: getService
  jigoshop.service.customer:
    class: Jigoshop\Service\Customer
    factory_service: jigoshop.factory.customer_service
    factory_method: getService
  jigoshop.admin:
    class: Jigoshop\Admin
    lazy: true
    arguments:
      - '@wpal'
      - '@jigoshop.admin.dashboard'
  jigoshop.admin.dashboard:
    class: Jigoshop\Admin\Dashboard
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.order'
      - '@jigoshop.service.product'
      - '@jigoshop.helper.styles'
    tags:
      - { name: jigoshop.admin.page }
  jigoshop.admin.reports:
    class: Jigoshop\Admin\Reports
    tags:
      - { name: jigoshop.admin.page }
  jigoshop.admin.settings:
    class: Jigoshop\Admin\Settings
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.helper.styles'
    tags:
      - { name: jigoshop.admin.page }
  jigoshop.admin.settings.general:
    class: Jigoshop\Admin\Settings\GeneralTab
    arguments:
      - '@jigoshop.options'
    tags:
      - { name: jigoshop.admin.settings.tab }
  jigoshop.admin.settings.shopping:
    class: Jigoshop\Admin\Settings\ShoppingTab
    arguments:
      - '@jigoshop.options'
      - '@jigoshop.helper.scripts'
    tags:
      - { name: jigoshop.admin.settings.tab }
  jigoshop.admin.settings.taxes:
    class: Jigoshop\Admin\Settings\TaxesTab
    arguments:
      - '@jigoshop.options'
      - '@jigoshop.service.tax'
      - '@jigoshop.helper.scripts'
    tags:
      - { name: jigoshop.admin.settings.tab }
  jigoshop.admin.system_info:
    class: Jigoshop\Admin\SystemInfo
    arguments:
      - '@wpal'
    tags:
      - { name: jigoshop.admin.page }
  jigoshop.admin.product.attributes:
    class: Jigoshop\Admin\Product\Attributes
    tags:
      - { name: jigoshop.admin.page }
