parameters: ~
services:
  jigoshop.service.order:
    class: Jigoshop\Service\OrderService
    factory: ['@jigoshop.factory.order_service', getService]
    lazy: true
  jigoshop.service.product:
    class: Jigoshop\Service\ProductService
    factory: ['@jigoshop.factory.product_service', getService]
    lazy: true
  jigoshop.service.product.variable:
    class: Jigoshop\Service\Product\VariableService
    factory: ['@jigoshop.factory.variable_product_service', getService]
  jigoshop.service.tax:
    class: Jigoshop\Service\TaxService
    factory: ['@jigoshop.factory.tax_service', getService]
    lazy: true
  jigoshop.service.customer:
    class: Jigoshop\Service\CustomerService
    factory: ['@jigoshop.factory.customer_service', getService]
  jigoshop.service.shipping:
    class: Jigoshop\Service\ShippingService
    factory: ['@jigoshop.factory.shipping_service', getService]
    lazy: true
  jigoshop.service.payment:
    class: Jigoshop\Service\PaymentService
    factory: ['@jigoshop.factory.payment_service', getService]
    lazy: true
  jigoshop.service.cart:
    class: Jigoshop\Service\CartService
    arguments:
      - '@wpal'
      - '@service_container'
      - '@jigoshop.options'
      - '@jigoshop.service.customer'
    calls:
      - ['init']
  jigoshop.service.email:
    class: Jigoshop\Service\EmailService
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.factory.email'
  jigoshop.service.coupon:
    class: Jigoshop\Service\CouponService
    lazy: true
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.factory.coupon'
