parameters: ~
services:
  jigoshop.service.order:
    class: Jigoshop\Service\OrderService
    factory_service: jigoshop.factory.order_service
    factory_method: getService
  jigoshop.service.product:
    class: Jigoshop\Service\ProductService
    factory_service: jigoshop.factory.product_service
    factory_method: getService
  jigoshop.service.product.variable:
    class: Jigoshop\Service\Product\VariableService
    factory_service: jigoshop.factory.variable_product_service
    factory_method: getService
  jigoshop.service.tax:
    class: Jigoshop\Service\TaxService
    factory_service: jigoshop.factory.tax_service
    factory_method: getService
  jigoshop.service.customer:
    class: Jigoshop\Service\CustomerService
    factory_service: jigoshop.factory.customer_service
    factory_method: getService
  jigoshop.service.shipping:
    class: Jigoshop\Service\ShippingService
    factory_service: jigoshop.factory.shipping_service
    factory_method: getService
  jigoshop.service.payment:
    class: Jigoshop\Service\PaymentService
    factory_service: jigoshop.factory.payment_service
    factory_method: getService
  jigoshop.service.cart:
    class: Jigoshop\Service\CartService
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.customer'
    tags:
      - { name: jigoshop.container_aware }
  jigoshop.service.email:
    class: Jigoshop\Service\EmailService
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.factory.email'
  jigoshop.service.coupon:
    class: Jigoshop\Service\CouponService
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.factory.coupon'
