parameters: ~
services:
  jigoshop.shipping.flat_rate:
    class: Jigoshop\Shipping\FlatRate
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.cart'
      - '@jigoshop.messages'
    tags:
      - { name: jigoshop.shipping.method }
  jigoshop.shipping.free_shipping:
    class: Jigoshop\Shipping\FreeShipping
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.cart'
      - '@jigoshop.messages'
    tags:
      - { name: jigoshop.shipping.method }
  jigoshop.shipping.local_pickup:
    class: Jigoshop\Shipping\LocalPickup
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.cart'
    tags:
      - { name: jigoshop.shipping.method }
