parameters: ~
services:
  jigoshop.shipping.flat_rate:
    class: Jigoshop\Shipping\FlatRate
    arguments:
      - '@jigoshop.options'
    tags:
      - { name: jigoshop.shipping.required_method }
  jigoshop.shipping.free_shipping:
    class: Jigoshop\Shipping\FreeShipping
    arguments:
      - '@jigoshop.options'
    tags:
      - { name: jigoshop.shipping.required_method }
